// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuAloEWoHZmWlHqlLPfzgs6ej25mvv0U',
    appId: '1:109650028736:web:48c7afb5bc29a907cc6525',
    messagingSenderId: '109650028736',
    projectId: 'tests-sushi-s-app',
    authDomain: 'tests-sushi-s-app.firebaseapp.com',
    storageBucket: 'tests-sushi-s-app.appspot.com',
    measurementId: 'G-WKV5W72VSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3MtEoRVuP2Tut33r5zmzDKVCuOPRfyA',
    appId: '1:109650028736:android:1334b341a30e627fcc6525',
    messagingSenderId: '109650028736',
    projectId: 'tests-sushi-s-app',
    storageBucket: 'tests-sushi-s-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhRgDgdC-lB8B42U7TQw3PJN3BxBaNaY',
    appId: '1:109650028736:ios:459b1e1b0d8b2b0bcc6525',
    messagingSenderId: '109650028736',
    projectId: 'tests-sushi-s-app',
    storageBucket: 'tests-sushi-s-app.appspot.com',
    iosBundleId: 'com.example.sushiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIhRgDgdC-lB8B42U7TQw3PJN3BxBaNaY',
    appId: '1:109650028736:ios:82e8f89311b4835acc6525',
    messagingSenderId: '109650028736',
    projectId: 'tests-sushi-s-app',
    storageBucket: 'tests-sushi-s-app.appspot.com',
    iosBundleId: 'com.example.sushiApp.RunnerTests',
  );
}
